2025-04-14 20:25:25,112 INFO    MainThread:2403862 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/yuvraj/YuvrajML/vjproject/vj_project/wandb/run-20250414_202525-uk537ewe/logs/debug.log
2025-04-14 20:25:25,112 INFO    MainThread:2403862 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/yuvraj/YuvrajML/vjproject/vj_project/wandb/run-20250414_202525-uk537ewe/logs/debug-internal.log
2025-04-14 20:25:25,112 INFO    MainThread:2403862 [wandb_init.py:init():781] calling init triggers
2025-04-14 20:25:25,112 INFO    MainThread:2403862 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'data_path': '/home/yuvraj/YuvrajML/vjproject/vj_project/data', 'num_classes': 256, 'class_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 'batch_size': 8, 'lr': 0.0001, 'weight_decay': 0.01, 'max_epochs': 5, 'img_size': (512, 512), '_wandb': {}}
2025-04-14 20:25:25,112 INFO    MainThread:2403862 [wandb_init.py:init():801] wandb.init() called while a run is active
2025-04-14 20:25:31,596 WARNING MsgRouterThr:2403862 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-14 20:25:31,598 INFO    MsgRouterThr:2403862 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
